global class OpportunityApiRestModel {
    /*global OpportunityApi oppApi {get;set;}
	
    global class OpportunityApi {
        global String eventType {get;set;}
        global String companyId {get;set;}
        global String centerCode {get;set;}
        global String operationId {get;set;}
        global String modality {get;set;}
        global String salesType {get;set;}
        global String creationDate {get;set;}
        global String successDate {get;set;}
        global String failureDate {get;set;}
        global String deliveryDate {get;set;}
        global String salesman {get;set;}
        global String customerId {get;set;}
        global String source {get;set;}
        global String motive {get;set;}
        global String rejectionReason {get;set;}
        
        List<Offer> offers {get;set;}
        List<TestDrive> testDrives {get;set;}
        List<NeedsDetection> needsDetections {get;set;}
    }
    
    global class Offer {
        List<ProductVehicle> productVehicles = new List<ProductVehicle>();
    }
    
    global class ProductVehicle {
        global String brand {get;set;}
        global String model {get;set;}
        global String version {get;set;}
        global String engine {get;set;}
        global String modelYear {get;set;}
        
        List<Service> services {get;set;}
    }
    
    global class Service {
        global String serviceType {get;set;}
        
        List<ServiceDetail> serviceDetails {get;set;}
    }
    
    global class ServiceDetail {
        global String description {get;set;}
    }
    
    global class EconomicSummary {
        global String currencyType {get;set;}		// 'currency' is reserved
        global String price {get;set;}
        global String discount {get;set;}
        global String total {get;set;}
    }
    
    global class Financing {
        global String financialCompany {get;set;}
        global String tariff {get;set;}
        global String amount {get;set;}
    }
    
    global class TestDrive {
        global String testDriveId {get;set;}
        global String creationDate {get;set;}
        global String deliveryDate {get;set;}
        global String endingDate {get;set;}
        global String vin {get;set;}
    }
    
    global class NeedsDetection {
        global String question {get;set;}
        global String answer {get;set;}
    }*/
}