global class SalesApiRestModel {
    /*global SalesApi salesApi {get;set;}
    
	global class SalesApi {
        global String eventType {get;set;}
        global String companyId {get;set;}
        global String salesCenterCode {get;set;}
        global String operationId {get;set;}
        global String modality {get;set;}
        global String salesType {get;set;}
        global String salesman {get;set;}
        global String customerId {get;set;}
        global String customerOwnerId {get;set;}
		global String invoiceDate {get;set;}
        
        // Offer Vehicle Payments
        global String currencyType {get;set;}		// 'currency' is reserved
        global String downPayment {get;set;}
        global String financedAmount {get;set;}
        global String usedVehicleEntryAmount {get;set;}
		global String finalEntry {get;set;}
        
        global List<Vehicle> vehicles {get;set;}
    }
    
    global class Vehicle {
        global String vin {get;set;}
		global String deliveryDate {get;set;}
        global String brand {get;set;}
        global String model {get;set;}
        global String modelCode {get;set;}
        global String version {get;set;}
        global String engine {get;set;}
        global String modelYear {get;set;}
        global String power {get;set;}
        global String engineCapacity {get;set;}
        global String fuel {get;set;}
		global String transmission {get;set;}
        global String engineLetter {get;set;}
        global String engineNumber {get;set;}
        global String engineCode {get;set;}
        global String registrationPlate {get;set;}
        global String registrationPlateDate {get;set;}
        global String kms {get;set;}
        global String warrantyStartDate {get;set;}
        global String warrantyEndDate {get;set;}
        global String warrantyExtensionStartDate {get;set;}
        global String warrantyExtensionEndDate {get;set;}
    }*/
}