global class VehicleExternalModel {

	global String brand {get;set;} 
    global String model {get;set;} 
    global String modelCode {get;set;}
    global String version {get;set;}
    global String engine {get;set;}
    global String modelYear {get;set;}
    global Integer power {get;set;}
    global Integer engineCapacity{get;set;}
    global String fuel {get;set;}
    global String fuelCode {get;set;}
    global String transmission {get;set;}
    global String engineLetter {get;set;}
    global String engineNumber {get;set;}
    global String engineCode {get;set;}
    global String gearBox {get;set;}
    global String registrationPlate {get;set;}
    global String registrationPlateDate {get;set;}
    global String vin {get;set;}
    global Double kms {get;set;}
    global String warrantyStartDate {get;set;}
    global String warrantyEndDate {get;set;}
    global String warrantyExtensionStartDate {get;set;}
    global String warrantyExtensionEndDate {get;set;}
    global String usedVehicleWarrantyStartDate {get;set;}
    global String usedVehicleWarrantyEndDate {get;set;}
    global String technicalVehicleClassification {get;set;}

}